// flow-typed signature: 0bb51c052c0ce975cb37bcea3735e659
// flow-typed version: <<STUB>>/aurora-utilities_vgit+https://github.com/carrieforde/Aurora-Utilities.git#master/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aurora-utilities'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aurora-utilities' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aurora-utilities/bin/au-config' {
  declare module.exports: any;
}

declare module 'aurora-utilities/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'aurora-utilities/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'aurora-utilities/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/babel-plugin-transform-es2015-modules-commonjs_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/eslint-config-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/eslint-plugin-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/eslint-plugin-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/prettier_v1.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/stylelint_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/stylelint-config-recommended-scss_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/stylelint-order_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/flow-typed/npm/stylelint-scss_vx.x.x' {
  declare module.exports: any;
}

declare module 'aurora-utilities/javascript/__tests__/validator.test' {
  declare module.exports: any;
}

declare module 'aurora-utilities/javascript/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aurora-utilities/bin/au-config.js' {
  declare module.exports: $Exports<'aurora-utilities/bin/au-config'>;
}
declare module 'aurora-utilities/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'aurora-utilities/coverage/lcov-report/block-navigation'>;
}
declare module 'aurora-utilities/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'aurora-utilities/coverage/lcov-report/prettify'>;
}
declare module 'aurora-utilities/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'aurora-utilities/coverage/lcov-report/sorter'>;
}
declare module 'aurora-utilities/flow-typed/npm/babel_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/babel_vx.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/babel-plugin-transform-es2015-modules-commonjs_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/babel-plugin-transform-es2015-modules-commonjs_vx.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/eslint-config-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/eslint-config-prettier_vx.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/eslint-plugin-flow_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/eslint-plugin-flow_vx.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/eslint-plugin-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/eslint-plugin-prettier_vx.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/jest_v22.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/prettier_v1.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/prettier_v1.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/stylelint_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/stylelint_vx.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/stylelint-config-recommended-scss_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/stylelint-config-recommended-scss_vx.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/stylelint-order_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/stylelint-order_vx.x.x'>;
}
declare module 'aurora-utilities/flow-typed/npm/stylelint-scss_vx.x.x.js' {
  declare module.exports: $Exports<'aurora-utilities/flow-typed/npm/stylelint-scss_vx.x.x'>;
}
declare module 'aurora-utilities/index' {
  declare module.exports: $Exports<'aurora-utilities'>;
}
declare module 'aurora-utilities/index.js' {
  declare module.exports: $Exports<'aurora-utilities'>;
}
declare module 'aurora-utilities/javascript/__tests__/validator.test.js' {
  declare module.exports: $Exports<'aurora-utilities/javascript/__tests__/validator.test'>;
}
declare module 'aurora-utilities/javascript/validator.js' {
  declare module.exports: $Exports<'aurora-utilities/javascript/validator'>;
}
